# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a184bc22dcd09b77b3350c25d5c7bf22fcba6217b1d316b29b6f57d57851a9c3b5d6421ce6039adfbc780082af313d558a97acc706d7fce89970e4518d5b68

test:
  secret_key_base: cb6d92a606d44a48c3d3d6aa89df65e313610352b7fc86dfbd3665beb8b5d9268e4ec0d1a18fc7c81d3cbae05769acf3d1add9f14a7d83c80474cf21525d3a4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
